version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: "deps(python)"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/project-template"
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: "deps(npm)"
    groups:
      npm-dependencies:
        patterns:
          - "*"
